# theme: jekyll-theme-minimal
remote_theme: "jeffreytse/jekyll-theme-yat"
title: Samuel Morelos
description: CSE 15L Submissions
favicon: <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
